### PR TITLE
Pii detection

### PR DESCRIPTION
**Pull request by misterbykl**
This PR includes developments that enables PII detection functionality. PII detection algorithm identifies **SSN** and **phone number** patterns in the value and applies masking where PII values are replaced with ###.

### What has been done?
- New JAVA module has been created using Maven.
- New stateful function name `pii-detection` has been added as a new module.
- New module configuration has been introduced in `pii-detection/module.yaml`.
- New Docker container has been created in `docker-compose.yml`.
- New Kafka topic, _pii-detection_, has been created for passing messages from `pii-detection` to `ingester`.

### CODE REVIEW

**Comment by dipanjanb** [comment]
Hi Emre,

While I'm setting up and reviewing the functionality as well as the code,
may I please request you to do the following:

1) Add documentation to the Java code
2) Cancel this PR and raise a PR for only the pii-detection folder
3) Add a README to the pii-detection folder outlining the steps that a user
would need to undertake to include PII Detection in the chain viz.
    a) Adding PII Detection to docker-compose.yml
    b) Modifying module.yaml in ingester service to point to pii-detection
topic as the ingress topic

We want to showcase your contribution as a fine example of how
easily/seamlessly users/developers can extend and enrich RTDL functionality
by adding their own stateful function modules in the chain.

Please feel free to reach out to me in case you have any questions.

Thanks & Regards,
Dipanjan

**Comment by dipanjanb** [comment]
No no - please do the following

a) IncomingMessage.java - you need to add support for the message_type
field. You also need to add support for stream_alt_id field. Refer to
IncomingMessage struct in ingester/ingester.go to understand. That
struct and types/IncomingMessage.java should be equivalent
b) If message_type value of incoming message is rtdl_205 then put the
message into the egress topic without any transformation since it is a
control message

No need to change any topic names

**Comment by dipanjanb** [comment]
For b) the change will be in function/PiiDetectionFn.java

**Comment by misterbykl** [comment]
> No no - please do the following a) IncomingMessage.java - you need to add support for the message_type field. You also need to add support for stream_alt_id field. Refer to IncomingMessage struct in ingester/ingester.go to understand. That struct and types/IncomingMessage.java should be equivalent b) If message_type value of incoming message is rtdl_205 then put the message into the egress topic without any transformation since it is a control message No need to change any topic names
> […](#)
> On Tue, 15 Mar 2022 at 15:06, Emre Baykal ***@***.***> wrote: Hi Emre, Identified one issue while running the program. The PII-Detection function doesn't seem to expect the message_type field in the original message body. However - this field can be present. Please add support for this field in the incoming message body. Also - if the message_type is rtdl_205 - then simply put that on the egress topic of PII-Detection without any modification. Message with type as rtdl_205 is a control message. Thanks & Regards, Dipanjan You mean Kafka topic will be 'rtdl_205' rather than 'pii-detection', and input message will be passed directly to Kafka? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

1. OK
2. So, the message will be produced to the same topic, 'pii-detection', again?

**Comment by misterbykl** [comment]
> Cancel this PR and raise a PR for only the pii-detection folder

How can I create PR for a specific folder? I followed your method that you mentioned here: https://github.com/realtimedatalake/rtdl/discussions/3#discussioncomment-2267097
Thanks.

**Comment by dipanjanb** [comment]
No - in case of message_type rtdl_205 (which is a control message) - no
pii-detection is necessary - it should simply be passed on to the next stage

**Comment by dipanjanb** [comment]
Do this -
1. Clone your fork to another location. Do not disturb the original location
2. In the new location - create another branch pr-branch from main
3. pr-branch should not show pii-detection folder
4. Copy pii-detection folder from previous file location to the new
file location
5. Now git status should show untracked for pii-detection in the new
location and pr-branch
6. Commit the change
7. Raise PR

Before you do the above - please first complete code update and README
in the pii-detection branch of your fork. Once you've done that - let
me know - I'll test the changes and review the code and README. Once I
confirm - you can raise the PR

**Comment by misterbykl** [comment]
> No - in case of message_type rtdl_205 (which is a control message) - no pii-detection is necessary - it should simply be passed on to the next stage

Sorry but it is still not clear to me. I am confused about the Kafka topic.

So, this is the Kafka flow when incoming message is NOT a control message:

    1. PIIDetection consumes 'ingress' topic, produces 'pii-detection' topic
    2. ingester.go consumes 'pii-detection' topic, produces 'egress' topic

What would be the flow when incoming message IS a control message?
Thanks.

**Comment by dipanjanb** [comment]
Same flow just don’t do any transformation

**Comment by dipanjanb** [comment]
Congrats Emre - the code is working as desired for both SSN and US format
phone number.

Please proceed to create PR as I had mentioned earlier.

**Comment by misterbykl** [comment]
@dipanjanb Thanks! By the way, new PR will not include any modification that's been made in `docker-compose.yml` if I follow the method you mentioned earlier. Is that OK for you?

**Comment by dipanjanb** [comment]
Exactly - and you’ve captured the instructions nicely in the README - so anybody looking to incorporate it should be able to do it easily

**Comment by dipanjanb** [comment]
Hi Emre,

The README looks great! The code comments are also good.

It's past midnight at my end - I will run the code tomorrow and let you
know.

Thanks & Regards,
Dipanjan

**Pull request closed without merging**
